name: "⚙️ Custom Issue"
description: "Submit a custom issue or suggestion for the FED website."
title: "[Custom]: <Brief description of the issue>"
labels: ["custom", "status: needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a custom issue for **FED-Frontend**. This template is intended for any requests or suggestions that do not fit into the bug report, feature request, or documentation categories.

  - type: input
    id: "issue_summary"
    attributes:
      label: "Issue Summary"
      description: "Provide a concise summary of the custom issue."
      placeholder: "E.g., Enhancement suggestion for search functionality"
    validations:
      required: true

  - type: textarea
    id: "issue_description"
    attributes:
      label: "Issue Description"
      description: "Describe the issue or suggestion in detail."
      placeholder: "Provide a detailed description, including context, use cases, or scenarios in which this issue arises or could be relevant."
    validations:
      required: true

  - type: textarea
    id: "proposed_solution"
    attributes:
      label: "Proposed Solution (Optional)"
      description: "If you have suggestions for addressing this issue, please describe them here."
      placeholder: "Describe your proposed solution or approach."

  - type: dropdown
    id: "priority"
    attributes:
      label: "Priority"
      description: "Select the priority level for this issue."
      options:
        - "High - Requires urgent attention"
        - "Medium - Should be addressed soon"
        - "Low - Can be addressed later"
    validations:
      required: true

  - type: checkboxes
    id: "category"
    attributes:
      label: "Category"
      description: "Select the category that best describes the issue."
      options:
        - label: "Enhancement"
        - label: "Refactor"
        - label: "Security"
        - label: "Design"
        - label: "Other"

  - type: textarea
    id: "additional_context"
    attributes:
      label: "Additional Context (Optional)"
      description: "Add any extra details, screenshots, or references that could help in understanding the issue."
      placeholder: "Provide any additional context or relevant information."

  - type: markdown
    attributes:
      value: |
        **Thank you for your submission!** We appreciate your input and will review your custom issue promptly.
